services:
  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - ${CONTAINERS_DISK_PATH}/ZeroTier/zerotier-one:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: host # Maybe change, so that it is able to comunicate with WireGuard
    # expose:
    #   - "9993/tcp"
    ports:
      - "9993:9993/udp"
  # zero-ui:
  #   image: zerotier/zero-ui:latest
  #   container_name: zt-main
  #   restart: unless-stopped
  #   depends_on:
  #     - zerotier
  #   volumes:
  #     - ${CONTAINERS_DISK_PATH}/ZeroTier/zerotier-one:/var/lib/zerotier-one
  #     - ${CONTAINERS_DISK_PATH}/ZeroTier/zt-data:/app/backend/data
  #   environment:
  #     - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
  #     - ZU_SECURE_HEADERS=true
  #     - ZU_DEFAULT_USERNAME=admin
  #     - ZU_DEFAULT_PASSWORD=zero-ui
  #   ports:
  #     - 4000:4000
  # npm:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
