services:
  clamav:
    image: clamav/clamav:stable
    container_name: clamav
    hostname: clamav
    restart: unless-stopped
    volumes:
      - "${PATH_TO_CONTAINERS}/ClamAV:/var/lib/clamav"
      - "${PATH_TO_CONTAINERS}/n8n/files:/scan/n8n:ro"
    healthcheck:
      test: [ "CMD-SHELL", "clamdscan --ping 3" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 180s
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    external: true
    name: nextcloud-net
