#
# WARNING: To install Immich, follow our guide: https://docs.immich.app/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    restart: unless-stopped
    depends_on:
      - database
      - redis
    ports:
      - '2283:2283'
    environment:
      TZ: Etc/UTC
      DB_HOSTNAME: database
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ${PATH_TO_CLOUD_DATA}/immich_data:/data
      - ${IMAGES_PATH}:/mnt_img:ro
      - ${VIDEOS_PATH}:/mnt_vid:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      disable: false
    secrets:
      - db_password
    networks:
      - immich-net

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    environment:
      TZ: Etc/UTC
    volumes:
      - ${PATH_TO_CONTAINERS}/Immich/model-cache:/cache
    healthcheck:
      disable: false
    networks:
      - immich-net

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich-net

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    restart: unless-stopped
    environment:
      TZ: Etc/UTC
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${PATH_TO_CONTAINERS}/Immich/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d immich"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db_password
    networks:
      - immich-net

secrets:
  db_password:
    file: "${PATH_TO_SECRETS}/Immich/db_password"

networks:
  immich-net:
    external: true
