# First user & pass: admin - admin

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "472:472"  # grafana:grafana dentro del contenedor

    ports:
      - "3001:3000"

    volumes:
      - "${PATH_TO_CONTAINERS}/Grafana/data:/var/lib/grafana"

    environment:
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: mariadb:3306
      GF_DATABASE_NAME__FILE: /run/secrets/grafana_db_name
      GF_DATABASE_USER__FILE: /run/secrets/grafana_db_user
      GF_DATABASE_PASSWORD__FILE: /run/secrets/grafana_db_password

    secrets:
      # - grafana_db_name
      # - grafana_db_user
      # - grafana_db_password
      - source: grafana_db_name
        target: grafana_db_name
        mode: 0444
      - source: grafana_db_user
        target: grafana_db_user
        mode: 0444
      - source: grafana_db_password
        target: grafana_db_password
        mode: 0444

    networks:
      - db-net

networks:
  db-net:
    external: true

secrets:
  grafana_db_name:
    file: ${PATH_TO_SECRETS}Grafana/grafana_db_name
  grafana_db_user:
    file: ${PATH_TO_SECRETS}/Grafana/grafana_db_user
  grafana_db_password:
    file: ${PATH_TO_SECRETS}/Grafana/grafana_db_password