services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - ${PATH_TO_CONTAINERS}/Syncthing/config:/config
      # - ${PATH_TO_YAMLS}:/YAMLs # Optional - To save the YAMLs
      - ${PATH_1}:${PATH_1}
      - ${PATH_2}:${PATH_2}
      - ${PATH_3}:${PATH_3}
      - ${PATH_4}:${PATH_4}
      # - ${PATH_5}:${PATH_5}
    ports:
      - "${SYNCTHING_GUI_BIND:-127.0.0.1}:8384:8384"
      # - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - files-net
      - cloud-net

networks:
  files-net:
    external: true
  cloud-net:
    external: true