services:
  samba:
    image: dperson/samba
    restart: unless-stopped
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    environment:
      - USERID=${UID} # User UID
      - GROUPID=${GID} # Group GID
      - TZ=Etc/UTC
    volumes:
      - ${PATH_TO_DOCUMENTS}:${PATH_TO_DOCUMENTS}
      - ${PATH_TO_CONTAINERS}:${PATH_TO_CONTAINERS}
      # - ${PATH_TO_DOCUMENTS_3}:${PATH_TO_DOCUMENTS_3}
    entrypoint:
      - /bin/sh
      - -c
      - >
        exec /sbin/tini -- /usr/bin/samba.sh
        -u "$(cat /run/secrets/samba_user);$(cat /run/secrets/samba_password)"
        -s "Documentos;${PATH_TO_DOCUMENTS};yes;no;no;$(cat /run/secrets/samba_user)"
        -s "Data Containers;${PATH_TO_CONTAINERS};yes;no;no;$(cat /run/secrets/samba_user)"
    #   -s "Linux;${PATH_TO_DOCUMENTS_3};yes;no;no;$(cat /run/secrets/samba_user)"
    secrets:
      - samba_user
      - samba_password
    networks:
       # - file-sharing-net
       - files-net

secrets:
  samba_user:
    file: "${PATH_TO_SECRETS}/Samba/samba_user"
  samba_password:
    file: "${PATH_TO_SECRETS}/Samba/samba_password"

networks:
  # file-sharing-net:
  #   external: true
  files-net:
    external: true