# version: '3.8'

services:
  samba:
    image: dperson/samba
    restart: unless-stopped
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    environment:
      - USERID=1000 # UID del usuario
      - GROUPID=1000 # GID del grupo
      - TZ=Etc/UTC   # Zona horaria
    volumes:
      - ${PATH_TO_DOCUMENTS}:${PATH_TO_DOCUMENTS}
    command: '-u "${USER_NAME};${USER_PASSWORD}" -s "${USER_NAME};${PATH_TO_DOCUMENTS};yes;no;no;${USER_NAME}"'
   #  command: '-u "${USER_NAME};${USER_PASSWORD}" -s "${USER_NAME};${PATH_TO_DOCUMENTS};yes;no;no;${USER_NAME};${USER_NAME};${USER_NAME};${USER_NAME}" -p'
   # command: >
   #   bash -c "
   #   chown -R 1000:1000 /mnt/usb/emm &&
   #   samba.sh -u 'emm;zxc' -s 'shared;/mnt/usb/emm;yes;no;no;emm'"
