services:
# NextCloud - Private
  nextcloud:
    container_name: nextcloud
    hostname: nextcloud
    image: nextcloud:latest
    restart: always
    ports:
      - 8080:80
    # depends_on:
    #   - mariadb # Only works if Nextcloud and MariaDB are on the same YAML
    volumes:
      # - /ruta/local/data:/var/www/html/data
      # - /ruta/local/apps:/var/www/html/apps
      # - /ruta/local/config:/var/www/html/config
      # - ${PATH_TO_CLOUD_DATA}:/var/www/html
      - ${PATH_TO_CLOUD_DATA}/nextcloud_data:/var/www/html/data
      - ${PATH_TO_CONTAINERS}/Nextcloud/apps:/var/www/html/apps
      - ${PATH_TO_CONTAINERS}/Nextcloud/config:/var/www/html/config
      - ${PATH_TO_DOCUMENTS}/Nextcloud/custom_apps:/var/www/html/custom_apps
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE_FILE=/run/secrets/db_mysql_name
      - MYSQL_USER_FILE=/run/secrets/db_mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_mysql_password
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS} # Domain Names or IPs (can also be private) separated with commas
      - REDIS_HOST=redis
      # - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD} # Optional in case you use another config
      # - OVERWRITECLIURL=${OVERWRITECLIURL} # ${NEXTCLOUD_TRUSTED_DOMAINS} with https://
      - OVERWRITEPROTOCOL=https
    secrets:
      - db_mysql_name
      - db_mysql_user
      - db_mysql_password
    networks:
      - db-net
      - nextcloud-net

secrets:
  db_mysql_name:
    file: "${PATH_TO_SECRETS}/NextCloud/db_mysql_name"
  db_mysql_user:
    file: "${PATH_TO_SECRETS}/NextCloud/db_mysql_user"
  db_mysql_password:
    file: "${PATH_TO_SECRETS}/NextCloud/db_mysql_password"

networks:
  db-net:
    external: true
  nextcloud-net:
    external: true