services:
  goaccess:
    image: justsky/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
      - |
        export BASIC_AUTH_USERNAME="$(cat /run/secrets/goaccess_user)"
        export BASIC_AUTH_PASSWORD="$(cat /run/secrets/goaccess_password)"
        exec tini -- /goan/start.sh
    environment:
        - TZ=Etc/UTC
        #- SKIP_ARCHIVED_LOGS=False #optional
        - BASIC_AUTH=True # False #optional
    secrets:
      - goaccess_user
      - goaccess_password
    ports:
        - '7880:7880'
    volumes:
        - ${PATH_TO_CONTAINERS}/NGINX-Proxy-Manager/data/npm_data/logs:/opt/log
        # - ${PATH_TO_CONTAINERS}/NGINX-Proxy-Manager/data/npm_data/logs:/opt/log
        # - ./data/npm_data/logs:/opt/log
        # - ./data/npm_data/logs/proxy-host-1_access.log:/opt/log/proxy-host-1_access.log
    networks:
      - proxy-net

secrets:
  goaccess_user:
    file: "${PATH_TO_SECRETS}/GoAccess/goaccess_user"
  goaccess_password:
    file: "${PATH_TO_SECRETS}/GoAccess/goaccess_password"

networks:
  proxy-net:
    external: true
    name: proxy-net