services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${PATH_TO_CONTAINERS}/Heimdall/config:/config
    ports:
      # - 81:80
      - 801:80
      - 4431:443
    restart: unless-stopped
    networks:
      - heimdall-net

  # heimdall_local:
  #   image: lscr.io/linuxserver/heimdall:latest
  #   container_name: heimdall_local
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=Etc/UTC
  #   volumes:
  #     - ${PATH_TO_CONTAINERS}/Heimdall/config_local:/config
  #   ports:
  #     # - 81:80
  #     - 802:80
  #     - 4432:443
  #   restart: unless-stopped
  #   networks:
  #     # - apps-net
  #     - heimdall-net

networks:
  # apps-net:
  #   external: true
  # isolated_1:
  #   external: true
  heimdall-net:
    external: true