# version: "2.1"

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SERVERURL=${SERVER_URL_OR_PRIVATE_IP} #optional
      - SERVERPORT=51820 #optional
      - PEERS=${NUMBER_OF_PEERS} # tells wireguard how many peers to connect
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ${PATH_TO_CONTAINERS}/WireGuard/wireguard-server/config:/config
      - ${PATH_TO_CONTAINERS}/WireGuard/wireguard-server/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped