# # ENTRA CON user y bitnami

# # version: '3.8'
# services:
#   # mariadb:
#   #   image: docker.io/bitnami/mariadb:11.3
#   #   restart: always
#   #   volumes:
#   #     - 'mariadb_data:/bitnami/mariadb'
#   #   environment:
#   #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
#   #     - ALLOW_EMPTY_PASSWORD=yes
#   #     - MARIADB_USER=bn_wordpress
#   #     - MARIADB_DATABASE=bitnami_wordpress
#   wordpress:
#     container_name: wordpress
#     # image: docker.io/bitnami/wordpress:6
#     image: docker.io/bitnami/wordpress:latest
#     restart: always
#     ports:
#       - '8090:8080'
#       - '4435:8443'
#     volumes:
#   #     - 'wordpress_data:/bitnami/wordpress'
#       - ${PATH_TO_CONTAINERS}/WordPress:/bitnami/wordpress
#     # depends_on:
#     #   - mariadb
#     environment:
#       # # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       # # - ALLOW_EMPTY_PASSWORD=yes
#       # - WORDPRESS_DATABASE_HOST=mariadb
#       # - WORDPRESS_DATABASE_PORT_NUMBER=3306
#       # # - WORDPRESS_DATABASE_USER=bn_wordpress
#       # # - WORDPRESS_DATABASE_NAME=bitnami_wordpress
#       # - WORDPRESS_DATABASE_USER=${MYSQL_WORDPRESS_USER}
#       # - WORDPRESS_DATABASE_NAME=${MYSQL_WORDPRESS_NAME}
#       # - WORDPRESS_DATABASE_PASSWORD=${MYSQL_WORDPRESS_PASS}
#       # WORDPRESS_DATABASE_HOST: mariadb
#       WORDPRESS_DATABASE_HOST: 172.28.0.5
#       WORDPRESS_DATABASE_PORT_NUMBER: 3306
#       WORDPRESS_DATABASE_USER: ${MYSQL_WORDPRESS_USER}
#       WORDPRESS_DATABASE_NAME: ${MYSQL_WORDPRESS_NAME}
#       WORDPRESS_DATABASE_PASSWORD: ${MYSQL_WORDPRESS_PASS}
#     networks:
#       - db-net
# # volumes:
# #   # mariadb_data:
# #   #   driver: local
# #   wordpress_data:
# #     driver: local

# networks:
#   db-net:
#     external: true
#     name: db-net

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      # - 8080:80
      - 8090:80
    environment:
      # WORDPRESS_DB_HOST: db
      # WORDPRESS_DB_USER: exampleuser
      # WORDPRESS_DB_PASSWORD: examplepass
      # WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_WORDPRESS_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_WORDPRESS_NAME}
    volumes:
      # - wordpress:/var/www/html
      - ${PATH_TO_CONTAINERS}/WordPress:/var/www/html
    networks:
      - db-net
    # depends_on:
    #   - mariadb

  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: exampledb
  #     MYSQL_USER: exampleuser
  #     MYSQL_PASSWORD: examplepass
  #     MYSQL_RANDOM_ROOT_PASSWORD: '1'
  #   volumes:
  #     - db:/var/lib/mysql

# volumes:
#   wordpress:
#   db:

networks:
  db-net:
    external: true
    name: db-net