services:
  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command:
      - 'exec /entrypoint.sh "$(cat /run/secrets/zt_network)"'
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ${PATH_TO_CONTAINERS}/ZeroTier/zerotier-one:/var/lib/zerotier-one
    secrets:
      - zt_network
    network_mode: host
    # Firewall: ufw deny 9993/udp o iptables -A INPUT -p udp --dport 9993 -j DROP

secrets:
  zt_network:
    file: "${PATH_TO_SECRETS}/ZeroTier/zt_network"
