services:
  app:
    container_name: nginxpm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      DB_MYSQL_HOST: mariadb
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_NGINX_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_NGINX_PASS}
      DB_MYSQL_NAME: ${MYSQL_NGINX_NAME}
    ports:
      # These ports are in format <host-port>:<container-port>
      # - '82:80' # Public HTTP Port
      # - '443:443' # Public HTTPS Port
      # - '81:81' # Admin Web Port
      - '40080:80' # Public HTTP Port
      - '40443:443' # Public HTTPS Port
      - '40081:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - ${PATH_TO_CONTAINERS}/NGINX-Proxy-Manager/data:/data
      - ${PATH_TO_CONTAINERS}/NGINX-Proxy-Manager/letsencrypt:/etc/letsencrypt
      - ${PATH_TO_CONTAINERS}/NGINX-Proxy-Manager/npm_logs:/var/log/nginx  
    # depends_on:
    #   - db
    #   # - mariadb
    networks:
      - app-network
  # db:
  #   # image: 'jc21/mariadb-aria:latest'
  #   # restart: unless-stopped
  #   external:
  #     name: mariadb
  #   networks:
  #     - app-network
  
networks:
  app-network:
    external: true
    name: app-network
#     driver: bridge
      
####
#
#     Default Administrator User login:
#     Email:    admin@example.com
#     Password: changeme
#
####
