tunnel: TU_TUNNEL_ID
credentials-file: /root/.cloudflared/TU_TUNNEL_ID.json
ingress:
  - hostname: filebrowser.WEB_DOMAIN_NAME
    service: http://localhost:8080
  - hostname: syncthing.WEB_DOMAIN_NAME
    service: http://localhost:8384
  - hostname: nextcloud.WEB_DOMAIN_NAME
    service: http://localhost:8081
  # - hostname: new.WEB_DOMAIN_NAME
  #   service: http://localhost:PORT_NEW_SERVICE
  - service: http_status:404
