# version: "3.8"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${PATH_TO_CONTAINERS}/MariaDB/data:/var/lib/mysql
      - ${PATH_TO_CONTAINERS}/MariaDB/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - app-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh --connect --innodb_initialized"]
      start_period: 40s
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mariadb-data:

networks:
  app-network:
    driver: bridge
    name: app-network
    external: true
