services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "1000:80"
    volumes:
      - ${PATH_TO_SYSTEM_BACKUP}/:/srv/BackUpSist
      - ${PATH_TO_DOCUMENTS_BACKUP}/:/srv/BackUpDocs
      - ${PATH_TO_DOCUMENTS}/:/srv/Documentos
      - ${PATH_TO_SERVER_HOME}/:/srv/data
      - ${PATH_TO_CONTAINERS}/FileBrowser/config/:/config
      - ${PATH_TO_CONTAINERS}/FileBrowser/database/:/database
      # - ${DISK_PATH_1}/srv:/srv/data_1
      # - /mnt:/srv/mnt
      # - /srv:/srv
    restart: unless-stopped
    networks:
      # - isolated_2
      # - filebrowser-net
      - files-net

networks:
  # isolated_2:
  #   external: true
  # filebrowser-net:
  #   external: true
  files-net:
    external: true